version: "3.8"

services:
  # 1. Reverse Proxy (Gateway)
  nginx:
    image: public.ecr.aws/nginx/nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./uploads:/var/www/uploads
    depends_on:
      - web
      - api
    restart: always
    deploy:
      resources:
        limits:
          memory: 200M

  # 2. Frontend (Next.js)
  web:
    build:
      context: apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://217.199.254.119
        NEXT_PUBLIC_YANDEX_MAPS_KEY: f5af7aa8-5a76-4586-a2b0-b59ed3e0a2ca
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://217.199.254.119
    deploy:
      resources:
        limits:
          memory: 800M
    expose:
      - "3000"

  # 3. Backend (FastAPI)
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: always
    env_file: apps/api/.env
    environment:
      - POSTGRES_SERVER=db
      - ENVIRONMENT=prod
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 800M
    expose:
      - "8000"

  # 4. Database
  db:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_secure_password # TODO: Change this!
      - POSTGRES_DB=estate_db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1.5G

volumes:
  postgres_data_prod:
